routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
 */

Route::group(['prefix' => '/'], function () {
	Route::get('/', ['as' => 'homePage', 'uses' => 'WebController@index']);
	Route::get('/most-popular', ['as' => 'mostPopularPage', 'uses' => 'WebController@most_popular']);
	Route::get('/tags', ['as' => 'tagsPage', 'uses' => 'WebController@tags']);
	Route::get('/categories', ['as' => 'categoriesPage', 'uses' => 'WebController@categories']);
	Route::get('/gallery', ['as' => 'galleryPage', 'uses' => 'WebController@gallery']);
	Route::get('/get-gallery-image/{id}', ['as' => 'getGalleryRoute', 'uses' => 'WebController@get_gallery_image']);
	Route::get('/contact-us', ['as' => 'contactUsPage', 'uses' => 'WebController@contact_us']);

	Route::get('/page/{slug}', ['as' => 'pagePage', 'uses' => 'WebController@page'])->where('slug', '[\w\d\-\_]+');

	Route::get('/category/{id}', ['as' => 'categoryPage', 'uses' => 'WebController@category']);
	Route::get('/tag/{id}', ['as' => 'tagPage', 'uses' => 'WebController@tag']);
	Route::get('/details/{slug}', ['as' => 'detailsPage', 'uses' => 'WebController@details'])->where('slug', '[\w\d\-\_]+');

	Route::post('/comment/{id}', ['as' => 'commentRoute', 'uses' => 'WebController@comment']);
	Route::post('/replay-comment/{id}', ['as' => 'replayCommentRoute', 'uses' => 'WebController@replay_comment']);

	Route::post('/search', ['as' => 'searchRoute', 'uses' => 'WebController@search']);
	Route::post('/subscribe', ['as' => 'subscribeRoute', 'uses' => 'WebController@subscribe']);

	Route::get('/makam', ['as' => 'makamPage', 'uses' => 'WebController@makam']);
	Route::get('/get-makam', ['as' => 'getMakam', 'uses' => 'WebController@get_makam']);

	Route::get('/jenazah', ['as' => 'jenazahPage', 'uses' => 'WebController@jenazah']);
	Route::get('/get-jenazah', ['as' => 'getJenazah', 'uses' => 'WebController@get_jenazah']);


	Route::group(['prefix' => 'dashboard', 'middleware' => ['user'], 'as' => 'dashboard.'], function () {
		Route::get('/', ['as' => 'dashboardPage', 'uses' => 'WebController@dashboard']);
		Route::get('/change-password', ['as' => 'editPasswordPage', 'uses' => 'WebController@edit_password']);
		Route::post('/update-password', ['as' => 'updatePasswordPage', 'uses' => 'WebController@update_password']);
		Route::get('/edit-profile', ['as' => 'editProfilePage', 'uses' => 'WebController@edit_profile']);
		Route::post('/update-profile/{id}', ['as' => 'updatePprofilePage', 'uses' => 'WebController@update_profile']);

		Route::get('/add-post', ['as' => 'addPostPage', 'middleware' => ['author'], 'uses' => 'WebController@add_post']);
		Route::post('/store-post', ['as' => 'storePostRoute', 'middleware' => ['author'], 'uses' => 'WebController@store_post']);
		Route::get('/edit-post/{id}', ['as' => 'editPostPage', 'middleware' => ['author'], 'uses' => 'WebController@edit_post']);
		Route::get('/view-post/{slug}', ['as' => 'viewPostPage', 'middleware' => ['author'], 'uses' => 'WebController@view_post']);
		Route::post('/update-post/{id}', ['as' => 'updatePostRoute', 'middleware' => ['author'], 'uses' => 'WebController@update_post']);
	});

	Route::get('/author-profile/{username}', ['as' => 'authorProfilePage', 'uses' => 'WebController@author_profile']);
});

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
 */

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin'], 'as' => 'admin.'], function () {
	Route::get('/dashboard', ['as' => 'dashboardRoute', 'uses' => 'DashboardController@index']);

	/*** For Category ***/
	Route::resource('categories', 'CategoryController');
	Route::get('/get-categories', ['as' => 'getCategoriesRoute', 'uses' => 'CategoryController@get']);
	Route::get('/categories/published/{id}', ['as' => 'publishedCategoriesRoute', 'uses' => 'CategoryController@published']);
	Route::get('/categories/unpublished/{id}', ['as' => 'unpublishedCategoriesRoute', 'uses' => 'CategoryController@unpublished']);

	/*** For Tag ***/
	Route::resource('tags', 'TagController');
	Route::get('/get-tags', ['as' => 'getTagsRoute', 'uses' => 'TagController@get']);
	Route::get('/tags/published/{id}', ['as' => 'publishedTagsRoute', 'uses' => 'TagController@published']);
	Route::get('/tags/unpublished/{id}', ['as' => 'unpublishedTagsRoute', 'uses' => 'TagController@unpublished']);

	/*** For Post ***/
	Route::resource('posts', 'PostController');
	Route::get('/get-posts', ['as' => 'getPostsRoute', 'uses' => 'PostController@get']);
	Route::get('/posts/published/{id}', ['as' => 'publishedPostsRoute', 'uses' => 'PostController@published']);
	Route::get('/posts/unpublished/{id}', ['as' => 'unpublishedPostsRoute', 'uses' => 'PostController@unpublished']);

	/*** For Subscriber ***/
	Route::resource('subscribers', 'SubscriberController');
	Route::get('/get-subscribers', ['as' => 'getSubscribersRoute', 'uses' => 'SubscriberController@get']);

	/*** For Setting ***/
	Route::resource('setting', 'SettingController');
	Route::post('/setting/logo/{id}', ['as' => 'settingLogoRoute', 'uses' => 'SettingController@logo']);
	Route::post('/setting/favicon/{id}', ['as' => 'settingFaviconRoute', 'uses' => 'SettingController@favicon']);
	Route::post('/setting/general/{id}', ['as' => 'settingGeneralRoute', 'uses' => 'SettingController@general']);
	Route::post('/setting/contact/{id}', ['as' => 'settingContactRoute', 'uses' => 'SettingController@contact']);
	Route::post('/setting/address/{id}', ['as' => 'settingAddressRoute', 'uses' => 'SettingController@address']);
	Route::post('/setting/social/{id}', ['as' => 'settingSocialRoute', 'uses' => 'SettingController@social']);
	Route::post('/setting/meta/{id}', ['as' => 'settingMetaRoute', 'uses' => 'SettingController@meta']);
	Route::post('/setting/gallery-meta/{id}', ['as' => 'settingGalleryMetaRoute', 'uses' => 'SettingController@gallery_meta']);

	/*** For Profile ***/
	Route::resource('profile', 'ProfileController');
	Route::post('/profile/avatar/{id}', ['as' => 'profileAvatarRoute', 'uses' => 'ProfileController@avatar']);
	Route::post('/profile/update-password', ['as' => 'profileUpdatePasswordRoute', 'uses' => 'ProfileController@update_password']);

	/*** For User ***/
	Route::resource('users', 'UserController');

	/*** For Comment ***/
	Route::resource('comments', 'CommentController');
	Route::get('/get-comments', ['as' => 'getCommentsRoute', 'uses' => 'CommentController@get']);
	Route::get('/comments/published/{id}', ['as' => 'publishedCommentsRoute', 'uses' => 'CommentController@published']);
	Route::get('/comments/unpublished/{id}', ['as' => 'unpublishedCommentsRoute', 'uses' => 'CommentController@unpublished']);

	/*** For Page ***/
	Route::resource('pages', 'PageController');
	Route::get('/get-pages', ['as' => 'getPagesRoute', 'uses' => 'PageController@get']);
	Route::get('/pages/published/{id}', ['as' => 'publishedPagesRoute', 'uses' => 'PageController@published']);
	Route::get('/pages/unpublished/{id}', ['as' => 'unpublishedPagesRoute', 'uses' => 'PageController@unpublished']);
	Route::get('/pages/destroy_pagefile/{id}', ['as' => 'destroyPagefile', 'uses' => 'PageController@destroy_pagefile']);

	Route::resource('makam', 'MakamController');
	Route::get('/get-makam', ['as' => 'getMakamRoute', 'uses' => 'MakamController@get']);
	Route::get('/makam/published/{id}', ['as' => 'publishedMakamRoute', 'uses' => 'MakamController@published']);
	Route::get('/makam/unpublished/{id}', ['as' => 'unpublishedMakamRoute', 'uses' => 'MakamController@unpublished']);

	Route::resource('jenazah', 'JenazahController');
	Route::get('/get-jenazah', ['as' => 'getJenazahRoute', 'uses' => 'JenazahController@get']);
	Route::get('/jenazah/published/{id}', ['as' => 'publishedJenazahRoute', 'uses' => 'JenazahController@published']);
	Route::get('/jenazah/unpublished/{id}', ['as' => 'unpublishedJenazahRoute', 'uses' => 'JenazahController@unpublished']);


	/*** For Gallery ***/
	Route::resource('galleries', 'GalleryController');
	Route::get('/get-galleries', ['as' => 'getGalleriesRoute', 'uses' => 'GalleryController@get']);
	Route::get('/galleries/published/{id}', ['as' => 'publishedGalleriesRoute', 'uses' => 'GalleryController@published']);
	Route::get('/galleries/unpublished/{id}', ['as' => 'unpublishedGalleriesRoute', 'uses' => 'GalleryController@unpublished']);

});

Auth::routes();

resources/views/admin/includes/flash_notification.blade.php
  <div class='col-xs-6 col-sm-6 col-md-3 alert bootstrap-growl-bottom-right alert-success' id='message_box' style='position: fixed; margin: 0px; z-index: 1080; bottom: -60px; right: 20px;'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button><i class='icon fa fa-check'></i>{{ !empty(Session::get('message')) ? Session::get('message') : '' }}</div>

  <div class='col-xs-6 col-sm-6 col-md-3 alert bootstrap-growl-bottom-right alert-warning' id='exception_box' style='position: fixed; margin: 0px; z-index: 1080; bottom: -60px; right: 20px;'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button><i class='icon fa fa-warning'></i>{{ !empty(Session::get('exception')) ? Session::get('exception') : '' }}</div>

resources/views/admin/includes/footer.blade.php
  <footer class="main-footer">
  	
  	{!! $setting->copyright !!}
  </footer>

resources/views/admin/includes/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>@yield('title')</title>
<!-- Tell the browser to be responsive to screen width -->
<link rel="shortcut icon" href="{{ asset('public/web/favicon/favicon.png') }}">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{ asset('public/admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('public/admin/bower_components/font-awesome/css/font-awesome.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{ asset('public/admin/bower_components/Ionicons/css/ionicons.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('public/admin/dist/css/AdminLTE.min.css') }}">
<!-- Parsley form validation -->
<link rel="stylesheet" href="{{ asset('public/admin/css/parsley.css') }}">
<!-- Custom Style -->
<link rel="stylesheet" href="{{ asset('public/admin/css/style.css') }}">
<!-- Summernote editor -->
<link href="{{ asset('public/admin/summernote/summernote.css') }}" rel="stylesheet">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
   folder instead of downloading all of them to reduce the load. -->
   <link rel="stylesheet" href="{{ asset('public/admin/dist/css/skins/_all-skins.min.css') }}">

   <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
   <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

resources/views/admin/includes/header.blade.php
<!-- Logo -->
<a href="{{ route('admin.dashboardRoute') }}" class="logo">
  <!-- mini logo for sidebar mini 50x50 pixels -->
  <span class="logo-mini"><b>D</b>ST</span>
  <!-- logo for regular state and mobile devices -->
  <span class="logo-lg"><b>{{ $setting->website_title }}</b></span>
</a>
<!-- Header Navbar: style can be found in header.less -->
<nav class="navbar navbar-static-top">
  <!-- Sidebar toggle button-->
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </a>

  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <!-- notification -->
     <!--  <li class="messages-menu"><a href="{{ route('admin.comments.index') }}" title="Comment"><i class="fa fa-comment-o"></i><span class="label label-warning">{{ $comments->count() }}</span></a></li>

      <li class="messages-menu"><a href="{{ route('admin.comments.index') }}" title="Post"><i class="fa fa-newspaper-o"></i><span class="label label-warning">{{ $posts->count() }}</span></a></li> -->
      <!-- /.notification -->

      <!-- frontend -->
      <li class="user user-menu">
        <a href="{{ route('homePage') }}" target="_blank">
          <img src="{{ asset('public/admin/image/frontend.png') }}" class="user-image img-responsive" alt="Frontend" width="25px">
          <span class="hidden-xs">Frontend</span>
        </a>
      </li>
      <!-- /.frontend -->

      <!-- user -->
      <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          @if(!empty(Auth::user()->avatar))
          <img src="{{ asset('public/avatar/' . Auth::user()->avatar) }}" class="user-image" alt="{{ Auth::user()->name }}">
          @else
          <img src="{{ asset('public/avatar/user.png') }}" class="user-image" alt="{{ Auth::user()->name }}">
          @endif
          <span class="hidden-xs">{{ Auth::user()->name }}</span>
        </a>
        <ul class="dropdown-menu">
          <!-- User image -->
          <li class="user-header">
            @if(!empty(Auth::user()->avatar))
            <img src="{{ asset('public/avatar/'. Auth::user()->avatar) }}" class="img-circle" alt="{{ Auth::user()->name }}">
            @else
            <img src="{{ asset('public/avatar/user.png') }}" class="img-circle" alt="{{ Auth::user()->name }}">
            @endif
            <p>
              {{ Auth::user()->name }} - {{ Auth::user()->role }}
              <small>Member Since {{ date("d F Y", strtotime(Auth::user()->created_at)) }} </small>
            </p>
          </li>
          <!-- Menu Footer-->
          <li class="user-footer">
            <div class="pull-left">
              <a href="{{ route('admin.profile.index') }}" class="btn btn-default btn-flat">Profile</a>
            </div>
            <div class="pull-right">
              <a href="{{ route('logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Sign out</a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
              </form>
            </div>
          </li>
        </ul>
      </li>
      <!-- /.user -->

      <!-- setting -->
      <li class="user user-menu"><a href="{{ route('admin.setting.index') }}"><span class="hidden-xs"><i class="fa fa-gears"></i></span></a></li>
      <!-- /.setting -->

    </ul>
  </div>
</nav>

resources/views/admin/includes/scripts.blade.php
<!-- jQuery 3 -->
<script src="{{ asset('public/admin/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('public/admin/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('public/admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('public/admin/bower_components/fastclick/lib/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('public/admin/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('public/admin/dist/js/demo.js') }}"></script>
<!-- Parsley form validation -->
<script src="{{ asset('public/admin/js/parsley.min.js') }}"></script>
<!-- Summernote editor -->
<script src="{{ asset('public/admin/summernote/summernote.js') }}"></script>
<script>
  $(document).ready(function () {
    $('.sidebar-menu').tree();
  })
</script>

<!-- Notification Message -->
@if (!empty(Session::get('message')))
<script>
  $(document).ready(function () {
    $('#message_box').animate({bottom: '60px'}, 1000);
    $("#message_box").fadeOut(4000);
  })
</script>
@endif

<!-- Notification Exception -->
@if (!empty(Session::get('exception')))
<script>
  $(document).ready(function () {
    $('#exception_box').animate({bottom: '60px'}, 1000);
    $("#exception_box").fadeOut(4000);
  })
</script>
@endif

<!-- Activate Menu -->
<script type="text/javascript">
 $('#mainMenu ul li').find('a').each(function () {
  if (document.location.href == $(this).attr('href')) {
    $(this).parents().addClass("active");
    $(this).addClass("active");
  }
});
</script>

<!-- For Modal Print -->
<script type="text/javascript">
  $('#print-button').on('click', function () {
    if ($('.print-modal').is(':visible')) {
      var modalId = $(event.target).closest('.print-modal').attr('id');
      $('body').css('visibility', 'hidden');
      $("#" + modalId).css('visibility', 'visible');
      $('#' + modalId).removeClass('print-modal');
      window.print();
      $('body').css('visibility', 'visible');
      $('#' + modalId).addClass('print-modal');
    } else {
      window.print();
    }
  });
</script>

<!-- For Div Print -->
<script type="text/javascript">
  function printDiv(printable_area) {
   var printContents = document.getElementById(printable_area).innerHTML;
   var originalContents = document.body.innerHTML;
   document.body.innerHTML = printContents;
   window.print();
   document.body.innerHTML = originalContents;
 }
</script>

<!-- For Tooltip -->
<script type="text/javascript">
  $('body').tooltip({selector: '[data-toggle="tooltip"]'});
</script>

resources/views/admin/includes/sidebar.blade.php
   <!-- sidebar: style can be found in sidebar.less -->
   <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        @if(!empty(Auth::user()->avatar))
        <img src="{{ asset('public/avatar/' . Auth::user()->avatar) }}" class="img-circle" alt="{{ Auth::user()->name }}">
        @else
        <img src="{{ asset('public/avatar/user.png') }}" class="img-circle" alt="{{ Auth::user()->name }}">
        @endif
      </div>
      <div class="pull-left info">
        <p>{{ Auth::user()->name }}</p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <div id="mainMenu">
      <ul class="sidebar-menu" data-widget="tree">
        <!-- <li class="{{ Request::is('admin/dashboard') ? "active" : '' }}"><a href="{{ route('admin.dashboardRoute') }}"><i class="fa fa-home"></i> <span>Dashboard</span></a></li> -->
        <li><a href="{{ route('admin.dashboardRoute') }}"><i class="fa fa-home text-purple"></i> <span>Dashboard</span></a></li>
        <!-- <li><a href="{{ route('admin.categories.index') }}"><i class="fa fa-paper-plane text-purple"></i> <span>Category</span></a></li> -->
        <li><a href="{{ route('admin.tags.index') }}"><i class="fa fa-tag text-purple"></i> <span>Tag</span></a></li>
        <li><a href="{{ route('admin.posts.index') }}"><i class="fa fa-newspaper-o text-purple"></i> <span>Berita & Pengumuman</span></a></li>
        <!-- <li><a href="{{ route('admin.users.index') }}"><i class="fa fa-users text-purple"></i> <span>User</span></a></li> -->
        <!-- <li><a href="{{ route('admin.comments.index') }}"><i class="fa fa-comment text-purple"></i> <span>Comment</span></a></li> -->
        <!-- <li><a href="{{ route('admin.subscribers.index') }}"><i class="fa fa-envelope text-purple"></i> <span>Subscriber</span></a></li> -->
        <li><a href="{{ route('admin.pages.index') }}"><i class="fa fa-file text-purple"></i> <span>Page</span></a></li>

        <li><a href="{{ route('admin.makam.index') }}"><i class="fa fa-institution text-purple"></i> <span>Makam</span></a></li>
        <li><a href="{{ route('admin.jenazah.index') }}"><i class="fa fa-hotel text-purple"></i> <span>Pelayanan Regis TPU</span></a></li>

        <li><a href="{{ route('admin.galleries.index') }}"><i class="fa fa-image text-purple"></i> <span>Gallery</span></a></li>
        <li><a href="{{ route('admin.setting.index') }}"><i class="fa fa-gears text-purple"></i> <span>Setting</span></a></li>
        <li class="header">LABELS</li>
        <li><a href="{{ route('admin.profile.index') }}"><i class="fa fa-user text-purple"></i> <span>Profile</span></a></li>
        <li>
          <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-lock text-purple"></i> <span>Sign out</span></a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
          </form>
        </li>
      </ul>
    </div>
  </section>
    <!-- /.sidebar -->